### ISSUE TITLE
Blacklists and whitelists in suites

### ISSUE THREAD

**Issue by danielsreichenbach** [henrikbjorn/PhpSpecCodeCoverageExtension#10]
I've been using the extension with a few projects, and in combination suites defined in `phpspec.yml`, and noticed that the `blacklist` and `whitelist` settings just seem to work on a global level in a project, but not per suite.

Configuration would be something like
```YAML
extensions:
    - PhpSpec\Extension\CodeCoverageExtension

code_coverage:
  format: html
  output: build/coverage

formatter.name: pretty

suites:
  DemoBundle:
    namespace: Acme\DemoBundle
    spec_path: src/Acme/DemoBundle
```

In this case, the `whitelist` and `blacklist` settings should apply to the defined `spec_path` for a suite, too.
