### ISSUE TITLE
Making it possible to disable code coverage

### ISSUE THREAD

**Issue by IvanChepurnyi** [henrikbjorn/PhpSpecCodeCoverageExtension#47]
At the moment if code coverage extension is enabled, code coverage is all the time enabled. Even if you don't have code coverage section in your configuration file. Would be great if it is disabled in case if no formatters are specified:
```yaml
code_coverage: 
  output: []
  format: []
```
